/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LeetCodeProblem } from './types';

export const DEFAULT_PROBLEMS: LeetCodeProblem[] = [
  // ==========================================
  // EASY PROBLEMS (1 to 40)
  // ==========================================
  {
    id: "1",
    title: "Two Sum",
    difficulty: "Easy",
    description: "Cho một mảng số nguyên `nums` và một số nguyên `target`, hãy trả về chỉ số của hai số sao cho tổng của chúng bằng `target`.\n\nBạn có thể giả định rằng mỗi đầu vào sẽ có đúng một giải pháp và không sử dụng cùng một phần tử hai lần.",
    codeTemplate: "function twoSum(nums: number[], target: number): number[] {\n    return [];\n};",
    solution: "function twoSum(nums: number[], target: number): number[] {\n    const map = new Map<number, number>();\n    for (let i = 0; i < nums.length; i++) {\n        const complement = target - nums[i];\n        if (map.has(complement)) {\n            return [map.get(complement)!, i];\n        }\n        map.set(nums[i], i);\n    }\n    return [];\n};",
    tags: ["Array", "Hash Table"],
    url: "https://leetcode.com/problems/two-sum/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function twoSum(nums: number[], target: number): number[] {\n    return [];\n};",
  },
  {
    id: "9",
    title: "Palindrome Number",
    difficulty: "Easy",
    description: "Xác định xem một số nguyên `x` có phải là số đối xứng (palindrome) hay không. Một số đối xuấn khi đọc từ trái qua phải hoặc từ phải qua trái đều giống nhau.",
    codeTemplate: "function isPalindrome(x: number): boolean {\n    return false;\n};",
    solution: "function isPalindrome(x: number): boolean {\n    if (x < 0) return false;\n    const str = x.toString();\n    return str === str.split('').reverse().join('');\n};",
    tags: ["Math"],
    url: "https://leetcode.com/problems/palindrome-number/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function isPalindrome(x: number): boolean {\n    return false;\n};",
  },
  {
    id: "13",
    title: "Roman to Integer",
    difficulty: "Easy",
    description: "Chuyển đổi một chuỗi chữ số La Mã `s` đại diện cho một số nguyên hợp lệ thành số nguyên thập phân tương ứng. Ví dụ: 'III' -> 3, 'IV' -> 4, 'IX' -> 9.",
    codeTemplate: "function romanToInt(s: string): number {\n    return 0;\n};",
    solution: "function romanToInt(s: string): number {\n    const roman: Record<string, number> = { I: 1, V: 5, X: 10, L: 50, C: 100, D: 500, M: 1000 };\n    let sum = 0;\n    for (let i = 0; i < s.length; i++) {\n        const cur = roman[s[i]];\n        const next = roman[s[i+1]];\n        if (next > cur) {\n            sum -= cur;\n        } else {\n            sum += cur;\n        }\n    }\n    return sum;\n};",
    tags: ["Hash Table", "Math", "String"],
    url: "https://leetcode.com/problems/roman-to-integer/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function romanToInt(s: string): number {\n    return 0;\n};",
  },
  {
    id: "14",
    title: "Longest Common Prefix",
    difficulty: "Easy",
    description: "Tìm chuỗi tiền tố chung dài nhất trong một mảng các chuỗi `strs`. Nếu không có tiền tố chung nào, trả về chuỗi rỗng `\"\"`.",
    codeTemplate: "function longestCommonPrefix(strs: string[]): string {\n    return \"\";\n};",
    solution: "function longestCommonPrefix(strs: string[]): string {\n    if (strs.length === 0) return \"\";\n    let prefix = strs[0];\n    for (let i = 1; i < strs.length; i++) {\n        while (strs[i].indexOf(prefix) !== 0) {\n            prefix = prefix.substring(0, prefix.length - 1);\n            if (prefix === \"\") return \"\";\n        }\n    }\n    return prefix;\n};",
    tags: ["String", "Trie"],
    url: "https://leetcode.com/problems/longest-common-prefix/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function longestCommonPrefix(strs: string[]): string {\n    return \"\";\n};",
  },
  {
    id: "20",
    title: "Valid Parentheses",
    difficulty: "Easy",
    description: "Cho một chuỗi `s` chỉ chứa các ký tự `'('`, `')'`, `'{'`, `'}'`, `'['` và `']'`, hãy xác định xem chuỗi đầu vào có tuân thủ đúng quy tắc đóng mở ngoặc hay không.",
    codeTemplate: "function isValid(s: string): boolean {\n    return false;\n};",
    solution: "function isValid(s: string): boolean {\n    const stack: string[] = [];\n    const map: { [key: string]: string } = { ')': '(', '}': '{', ']': '[' };\n    for (let char of s) {\n        if (char === '(' || char === '{' || char === '[') {\n            stack.push(char);\n        } else {\n            if (stack.pop() !== map[char]) return false;\n        }\n    }\n    return stack.length === 0;\n};",
    tags: ["String", "Stack"],
    url: "https://leetcode.com/problems/valid-parentheses/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function isValid(s: string): boolean {\n    return false;\n};",
  },
  {
    id: "21",
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    description: "Trộn hai danh sách liên kết đã được sắp xếp tăng dần thành một danh sách liên kết mới duy nhất được sắp xếp tăng dần.",
    codeTemplate: "function mergeTwoLists(list1: ListNode | null, list2: ListNode | null): ListNode | null {\n    return null;\n};",
    tags: ["Linked List", "Recursion"],
    url: "https://leetcode.com/problems/merge-two-sorted-lists/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function mergeTwoLists(list1: ListNode | null, list2: ListNode | null): ListNode | null {\n    return null;\n};",
  },
  {
    id: "26",
    title: "Remove Duplicates from Sorted Array",
    difficulty: "Easy",
    description: "Loại bỏ các phần tử trùng lặp trong một mảng số nguyên đã sắp xếp `nums` sao cho mỗi phần tử chỉ xuất hiện một lần duy nhất. Trả về số lượng phần tử độc nhất.",
    codeTemplate: "function removeDuplicates(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Two Pointers"],
    url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function removeDuplicates(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "27",
    title: "Remove Element",
    difficulty: "Easy",
    description: "Loại bỏ tất cả các bản ghi của một giá trị `val` trong mảng `nums` tại chỗ (in-place) và trả về số phần tử còn lại của mảng sau khi xóa.",
    codeTemplate: "function removeElement(nums: number[], val: number): number {\n    return 0;\n};",
    tags: ["Array", "Two Pointers"],
    url: "https://leetcode.com/problems/remove-element/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function removeElement(nums: number[], val: number): number {\n    return 0;\n};",
  },
  {
    id: "28",
    title: "Find Index of First Needle in Haystack",
    difficulty: "Easy",
    description: "Trả về chỉ số xuất hiện đầu tiên của chuỗi `needle` trong chuỗi `haystack`, hoặc trả về `-1` nếu `needle` không phải là một phần của `haystack`.",
    codeTemplate: "function strStr(haystack: string, needle: string): number {\n    return -1;\n};",
    tags: ["Two Pointers", "String", "String Matching"],
    url: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function strStr(haystack: string, needle: string): number {\n    return -1;\n};",
  },
  {
    id: "35",
    title: "Search Insert Position",
    difficulty: "Easy",
    description: "Cho một mảng đã sắp xếp và một giá trị mục tiêu, trả về chỉ số nếu tìm thấy mục tiêu. Nếu không, hãy trả về chỉ số thích hợp mà mục tiêu sẽ được chèn vào để bảo toàn trật tự sắp xếp.",
    codeTemplate: "function searchInsert(nums: number[], target: number): number {\n    return 0;\n};",
    tags: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/search-insert-position/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function searchInsert(nums: number[], target: number): number {\n    return 0;\n};",
  },
  {
    id: "58",
    title: "Length of Last Word",
    difficulty: "Easy",
    description: "Cho một chuỗi `s` gồm các từ và khoảng trắng, hãy tìm độ dài của từ cuối cùng nằm trong chuỗi đó.",
    codeTemplate: "function lengthOfLastWord(s: string): number {\n    return 0;\n};",
    tags: ["String"],
    url: "https://leetcode.com/problems/length-of-last-word/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function lengthOfLastWord(s: string): number {\n    return 0;\n};",
  },
  {
    id: "66",
    title: "Plus One",
    difficulty: "Easy",
    description: "Cộng thêm 1 vào một số nguyên không âm lớn được đại diện bởi một mảng các chữ số `digits`. Trả về mảng các chữ số sau khi cộng.",
    codeTemplate: "function plusOne(digits: number[]): number[] {\n    return [];\n};",
    tags: ["Array", "Math"],
    url: "https://leetcode.com/problems/plus-one/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function plusOne(digits: number[]): number[] {\n    return [];\n};",
  },
  {
    id: "67",
    title: "Add Binary",
    difficulty: "Easy",
    description: "Cho hai chuỗi nhị phân `a` và `b`, trả về tổng nhị phân của chúng dưới dạng một chuỗi nhị phân chung.",
    codeTemplate: "function addBinary(a: string, b: string): string {\n    return \"\";\n};",
    tags: ["Math", "String", "Bit Manipulation"],
    url: "https://leetcode.com/problems/add-binary/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function addBinary(a: string, b: string): string {\n    return \"\";\n};",
  },
  {
    id: "69",
    title: "Sqrt(x)",
    difficulty: "Easy",
    description: "Tính toán và trả về phần nguyên căn bậc hai của số nguyên không âm `x` mà không sử dụng bất kỳ hàm số mũ hoặc hàm căn thức có sẵn nào.",
    codeTemplate: "function mySqrt(x: number): number {\n    return 0;\n};",
    tags: ["Math", "Binary Search"],
    url: "https://leetcode.com/problems/sqrtx/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function mySqrt(x: number): number {\n    return 0;\n};",
  },
  {
    id: "70",
    title: "Climbing Stairs",
    difficulty: "Easy",
    description: "Bạn đang leo lên một cầu thang có `n` bậc. Mỗi lần bạn có thể leo `1` hoặc `2` bậc. Có bao nhiêu cách kết hợp khác nhau để bạn leo lên đến đỉnh bậc?",
    codeTemplate: "function climbStairs(n: number): number {\n    return 0;\n};",
    tags: ["Math", "Dynamic Programming", "Memoization"],
    url: "https://leetcode.com/problems/climbing-stairs/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function climbStairs(n: number): number {\n    return 0;\n};",
  },
  {
    id: "83",
    title: "Remove Duplicates from Sorted List",
    difficulty: "Easy",
    description: "Cho đầu danh sách liên kết đã sắp xếp, xóa tất cả các nút trùng lặp sao cho mỗi phần tử chỉ xuất hiện duy nhất 1 lần.",
    codeTemplate: "function deleteDuplicates(head: ListNode | null): ListNode | null {\n    return null;\n};",
    tags: ["Linked List"],
    url: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function deleteDuplicates(head: ListNode | null): ListNode | null {\n    return null;\n};",
  },
  {
    id: "88",
    title: "Merge Sorted Array",
    difficulty: "Easy",
    description: "Hợp nhất hai mảng số nguyên đã sắp xếp `nums1` và `nums2` thành một mảng tăng dần duy nhất được lưu tại chỗ ngay trong mảng `nums1`.",
    codeTemplate: "function merge(nums1: number[], m: number, nums2: number[], n: number): void {\n    \n};",
    tags: ["Array", "Two Pointers", "Sorting"],
    url: "https://leetcode.com/problems/merge-sorted-array/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function merge(nums1: number[], m: number, nums2: number[], n: number): void {\n    \n};",
  },
  {
    id: "94",
    title: "Binary Tree Inorder Traversal",
    difficulty: "Easy",
    description: "Cho nút gốc của một cây nhị phân, hãy trả về kết quả duyệt cây theo thứ tự Trung Thứ (Inorder traversal).",
    codeTemplate: "function inorderTraversal(root: TreeNode | null): number[] {\n    return [];\n};",
    tags: ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function inorderTraversal(root: TreeNode | null): number[] {\n    return [];\n};",
  },
  {
    id: "100",
    title: "Same Tree",
    difficulty: "Easy",
    description: "Cho gốc của hai cây nhị phân `p` và `q`, hãy viết hàm kiểm tra xem chúng có thực sự giống hệt nhau về cả cấu trúc lẫn giá trị tại các nút hay không.",
    codeTemplate: "function isSameTree(p: TreeNode | null, q: TreeNode | null): boolean {\n    return false;\n};",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/same-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function isSameTree(p: TreeNode | null, q: TreeNode | null): boolean {\n    return false;\n};",
  },
  {
    id: "101",
    title: "Symmetric Tree",
    difficulty: "Easy",
    description: "Kiểm tra xem một cây nhị phân có đối xứng qua trục tâm của nó hay không (tức là cấu trúc đối gương phản chiếu).",
    codeTemplate: "function isSymmetric(root: TreeNode | null): boolean {\n    return false;\n};",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/symmetric-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function isSymmetric(root: TreeNode | null): boolean {\n    return false;\n};",
  },
  {
    id: "104",
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    description: "Tìm độ sâu tối đa (chiều cao) của một cây nhị phân đại diện cho số nút dọc theo con đường dài nhất từ nút gốc đến nút lá biên xa nhất.",
    codeTemplate: "function maxDepth(root: TreeNode | null): number {\n    return 0;\n};",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function maxDepth(root: TreeNode | null): number {\n    return 0;\n};",
  },
  {
    id: "108",
    title: "Convert Sorted Array to BST",
    difficulty: "Easy",
    description: "Chuyển đổi một mảng số nguyên đã sắp xếp tăng dần thành một Cây tìm kiếm nhị phân có độ cao cân bằng (Height-Balanced BST).",
    codeTemplate: "function sortedArrayToBST(nums: number[]): TreeNode | null {\n    return null;\n};",
    tags: ["Array", "Divide and Conquer", "Tree", "Binary Search Tree", "Binary Tree"],
    url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function sortedArrayToBST(nums: number[]): TreeNode | null {\n    return null;\n};",
  },
  {
    id: "110",
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    description: "Cho một cây nhị phân, hãy xác định xem nó có phải là một cây nhị phân cân bằng độ cao hay không (chênh lệch chiều cao hai bên không quá 1).",
    codeTemplate: "function isBalanced(root: TreeNode | null): boolean {\n    return false;\n};",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/balanced-binary-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function isBalanced(root: TreeNode | null): boolean {\n    return false;\n};",
  },
  {
    id: "111",
    title: "Minimum Depth of Binary Tree",
    difficulty: "Easy",
    description: "Tìm chiều sâu nhỏ nhất từ nút gốc đến nút lá gần nhất của cây nhị phân.",
    codeTemplate: "function minDepth(root: TreeNode | null): number {\n    return 0;\n};",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/minimum-depth-of-binary-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function minDepth(root: TreeNode | null): number {\n    return 0;\n};",
  },
  {
    id: "112",
    title: "Path Sum",
    difficulty: "Easy",
    description: "Cho gốc cây nhị phân và một giá trị `targetSum`, kiểm tra xem có đường dẫn từ gốc đến một nút lá nào mà tổng giá trị các nút bằng `targetSum` không.",
    codeTemplate: "function hasPathSum(root: TreeNode | null, targetSum: number): boolean {\n    return false;\n};",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/path-sum/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function hasPathSum(root: TreeNode | null, targetSum: number): boolean {\n    return false;\n};",
  },
  {
    id: "118",
    title: "Pascal's Triangle",
    difficulty: "Easy",
    description: "Cho một số nguyên`numRows`, trả về `numRows` hàng đầu tiên của kiến trúc Tam giác Pascal nổi tiếng.",
    codeTemplate: "function generate(numRows: number): number[][] {\n    return [];\n};",
    tags: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/pascals-triangle/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function generate(numRows: number): number[][] {\n    return [];\n};",
  },
  {
    id: "119",
    title: "Pascal's Triangle II",
    difficulty: "Easy",
    description: "Cho một chỉ số dòng số nguyên `rowIndex`, trả về đúng dòng thứ `rowIndex` đó trong kiến trúc Tam giác Pascal (tính từ dòng 0).",
    codeTemplate: "function getRow(rowIndex: number): number[] {\n    return [];\n};",
    tags: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/pascals-triangle-ii/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function getRow(rowIndex: number): number[] {\n    return [];\n};",
  },
  {
    id: "121",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    description: "Tìm mức lợi nhuận tối đa thu được bằng cách mua vào cổ phiếu tại 1 ngày trong mảng `prices` và bán ra tại một ngày trong tương lai.",
    codeTemplate: "function maxProfit(prices: number[]): number {\n    return 0;\n};",
    solution: "function maxProfit(prices: number[]): number {\n    let minPrice = Infinity;\n    let maxProfit = 0;\n    for (let i = 0; i < prices.length; i++) {\n        if (prices[i] < minPrice) {\n            minPrice = prices[i];\n        } else if (prices[i] - minPrice > maxProfit) {\n            maxProfit = prices[i] - minPrice;\n        }\n    }\n    return maxProfit;\n};",
    tags: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function maxProfit(prices: number[]): number {\n    return 0;\n};",
  },
  {
    id: "125",
    title: "Valid Palindrome",
    difficulty: "Easy",
    description: "Chuyển toàn bộ các chữ trong chuỗi `s` thành chữ thường, loại bỏ mọi ký tự không phải chữ và số, sau đó xác định xem chuỗi còn lại có phải chuỗi đối xứng không.",
    codeTemplate: "function isPalindrome(s: string): boolean {\n    return false;\n};",
    tags: ["Two Pointers", "String"],
    url: "https://leetcode.com/problems/valid-palindrome/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function isPalindrome(s: string): boolean {\n    return false;\n};",
  },
  {
    id: "136",
    title: "Single Number",
    difficulty: "Easy",
    description: "Trong một mảng số nguyên phi rỗng, mọi phần tử đều xuất hiện hai lần ngoại trừ một phần tử duy nhất cô độc. Hãy tìm ra phần tử duy nhất đó.",
    codeTemplate: "function singleNumber(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Bit Manipulation"],
    url: "https://leetcode.com/problems/single-number/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function singleNumber(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "141",
    title: "Linked List Cycle",
    difficulty: "Easy",
    description: "Xác định xem một danh sách liên kết có tồn tại chu trình (vòng lặp vô hạn tuần hoàn nút) bên trong hay không.",
    codeTemplate: "function hasCycle(head: ListNode | null): boolean {\n    return false;\n};",
    tags: ["Hash Table", "Linked List", "Two Pointers"],
    url: "https://leetcode.com/problems/linked-list-cycle/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function hasCycle(head: ListNode | null): boolean {\n    return false;\n};",
  },
  {
    id: "160",
    title: "Intersection of Two Linked Lists",
    difficulty: "Easy",
    description: "Tìm nút giao nhau nơi hai danh sách liên kết gặp nhau và bắt đầu dùng chung các nút tiếp theo.",
    codeTemplate: "function getIntersectionNode(headA: ListNode | null, headB: ListNode | null): ListNode | null {\n    return null;\n};",
    tags: ["Hash Table", "Linked List", "Two Pointers"],
    url: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function getIntersectionNode(headA: ListNode | null, headB: ListNode | null): ListNode | null {\n    return null;\n};",
  },
  {
    id: "169",
    title: "Majority Element",
    difficulty: "Easy",
    description: "Cho mảng `nums` chứa kích cỡ n phần tử, tìm phần tử xuất hiện nhiều nhất (với số lần xuất hiện nhiều hơn `n / 2` lần).",
    codeTemplate: "function majorityElement(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Hash Table", "Divide and Conquer", "Sorting", "Counting"],
    url: "https://leetcode.com/problems/majority-element/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function majorityElement(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "191",
    title: "Number of 1 Bits",
    difficulty: "Easy",
    description: "Viết một hàm nhận một số nguyên không âm và trả về số lượng bit '1' có trong biểu diễn nhị phân của số đó (độ trọng Hamming).",
    codeTemplate: "function hammingWeight(n: number): number {\n    return 0;\n};",
    tags: ["Divide and Conquer", "Bit Manipulation"],
    url: "https://leetcode.com/problems/number-of-1-bits/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function hammingWeight(n: number): number {\n    return 0;\n};",
  },
  {
    id: "202",
    title: "Happy Number",
    difficulty: "Easy",
    description: "Xác định xem một số `n` có phải là số hạnh phúc hay không. Quy trình thay thế số bằng tổng bình phương các chữ số của nó, lặp lại đến khi bằng 1.",
    codeTemplate: "function isHappy(n: number): boolean {\n    return false;\n};",
    tags: ["Hash Table", "Math", "Two Pointers"],
    url: "https://leetcode.com/problems/happy-number/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function isHappy(n: number): boolean {\n    return false;\n};",
  },
  {
    id: "206",
    title: "Reverse Linked List",
    difficulty: "Easy",
    description: "Đảo ngược một danh sách liên kết đơn (ví dụ: 1 -> 2 -> 3 -> 4 thành 4 -> 3 -> 2 -> 1).",
    codeTemplate: "function reverseList(head: ListNode | null): ListNode | null {\n    return null;\n};",
    tags: ["Linked List", "Recursion"],
    url: "https://leetcode.com/problems/reverse-linked-list/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function reverseList(head: ListNode | null): ListNode | null {\n    return null;\n};",
  },
  {
    id: "217",
    title: "Contains Duplicate",
    difficulty: "Easy",
    description: "Cho một mảng các số nguyên `nums`, hãy trả về `true` nếu có bất kỳ giá trị nào xuất hiện ít nhất hai lần trong mảng và trả về `false` nếu mọi phần tử đều khác nhau.",
    codeTemplate: "function containsDuplicate(nums: number[]): boolean {\n    return false;\n};",
    tags: ["Array", "Hash Table", "Sorting"],
    url: "https://leetcode.com/problems/contains-duplicate/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function containsDuplicate(nums: number[]): boolean {\n    return false;\n};",
  },
  {
    id: "226",
    title: "Invert Binary Tree",
    difficulty: "Easy",
    description: "Lật ngược một cây nhị phân (tạo phản chiếu gương cho mọi nút con nhánh trái và phải của cây).",
    codeTemplate: "function invertTree(root: TreeNode | null): TreeNode | null {\n    return null;\n};",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/invert-binary-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function invertTree(root: TreeNode | null): TreeNode | null {\n    return null;\n};",
     },
  {
    id: "242",
    title: "Valid Anagram",
    difficulty: "Easy",
    description: "Cho hai chuỗi `s` và `t`, kiểm tra xem chuỗi `t` có phải chuỗi đảo chữ (anagram) của chuỗi `s` hay không.",
    codeTemplate: "function isAnagram(s: string, t: string): boolean {\n    return false;\n};",
    tags: ["Hash Table", "String", "Sorting"],
    url: "https://leetcode.com/problems/valid-anagram/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function isAnagram(s: string, t: string): boolean {\n    return false;\n};",
  },
  {
    id: "704",
    title: "Binary Search",
    difficulty: "Easy",
    description: "Cho một mảng số nguyên đã sắp xếp tăng dần và một số mục tiêu `target`, hãy tìm chỉ mục của nó trong mảng qua thuật giải O(log n).",
    codeTemplate: "function search(nums: number[], target: number): number {\n    return -1;\n};",
    solution: "function search(nums: number[], target: number): number {\n    let left = 0;\n    let right = nums.length - 1;\n    while (left <= right) {\n        const mid = Math.floor((left + right) / 2);\n        if (nums[mid] === target) return mid;\n        else if (nums[mid] < target) left = mid + 1;\n        else right = mid - 1;\n    }\n    return -1;\n};",
    tags: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/binary-search/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function search(nums: number[], target: number): number {\n    return -1;\n};",
  },

  // ==========================================
  // MEDIUM PROBLEMS (41 to 85)
  // ==========================================
  {
    id: "2",
    title: "Add Two Numbers",
    difficulty: "Medium",
    description: "Cho hai danh sách liên kết phi rỗng đại diện cho hai số nguyên không âm. Các chữ số được lưu trữ theo thứ tự ngược lại và mỗi nút chứa một chữ số đơn. Cộng hai số và trả về dưới dạng một danh sách liên kết mới.",
    codeTemplate: "function addTwoNumbers(l1: ListNode | null, l2: ListNode | null): ListNode | null {\n    return null;\n};",
    tags: ["Linked List", "Math", "Recursion"],
    url: "https://leetcode.com/problems/add-two-numbers/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function addTwoNumbers(l1: ListNode | null, l2: ListNode | null): ListNode | null {\n    return null;\n};",
  },
  {
    id: "3",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    description: "Tìm độ dài của chuỗi con dài nhất không chứa bất kỳ ký tự nào lặp lại trong chuỗi `s`.",
    codeTemplate: "function lengthOfLongestSubstring(s: string): number {\n    return 0;\n};",
    tags: ["Hash Table", "String", "Sliding Window"],
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function lengthOfLongestSubstring(s: string): number {\n    return 0;\n};",
  },
  {
    id: "5",
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    description: "Tìm chuỗi con đối xứng ngắn/dài nhất nằm trong chuỗi `s` cho trước.",
    codeTemplate: "function longestPalindrome(s: string): string {\n    return \"\";\n};",
    tags: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/longest-palindromic-substring/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function longestPalindrome(s: string): string {\n    return \"\";\n};",
  },
  {
    id: "11",
    title: "Container With Most Water",
    difficulty: "Medium",
    description: "Tìm hai đường thẳng trong mảng chiều cao `height` sao cho kết hợp với trục hoành tạo thành một thùng chứa nước chứa được dung tích nhiều nước nhất.",
    codeTemplate: "function maxArea(height: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Two Pointers", "Greedy"],
    url: "https://leetcode.com/problems/container-with-most-water/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function maxArea(height: number[]): number {\n    return 0;\n};",
  },
  {
    id: "15",
    title: "3Sum",
    difficulty: "Medium",
    description: "Cho một mảng số nguyên `nums`, trả về tất cả các bộ ba độc lập `[nums[i], nums[j], nums[k]]` sao cho tổng của chúng cộng lại bằng đúng 0.",
    codeTemplate: "function threeSum(nums: number[]): number[][] {\n    return [];\n};",
    solution: "function threeSum(nums: number[]): number[][] {\n    const results: number[][] = [];\n    nums.sort((a, b) => a - b);\n    for (let i = 0; i < nums.length - 2; i++) {\n        if (i > 0 && nums[i] === nums[i - 1]) continue;\n        let left = i + 1, right = nums.length - 1;\n        while (left < right) {\n            const sum = nums[i] + nums[left] + nums[right];\n            if (sum === 0) {\n                results.push([nums[i], nums[left], nums[right]]);\n                while (left < right && nums[left] === nums[left + 1]) left++;\n                while (left < right && nums[right] === nums[right - 1]) right--;\n                left++; right--;\n            } else if (sum < 0) left++;\n            else right--;\n        }\n    }\n    return results;\n};",
    tags: ["Array", "Two Pointers", "Sorting"],
    url: "https://leetcode.com/problems/3sum/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function threeSum(nums: number[]): number[][] {\n    return [];\n};",
  },
  {
    id: "19",
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    description: "Xóa nút thứ `n` tính từ cuối danh sách liên kết đơn lên và trả về đầu danh sách.",
    codeTemplate: "function removeNthFromEnd(head: ListNode | null, n: number): ListNode | null {\n    return null;\n};",
    tags: ["Linked List", "Two Pointers"],
    url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function removeNthFromEnd(head: ListNode | null, n: number): ListNode | null {\n    return null;\n};",
  },
  {
    id: "22",
    title: "Generate Parentheses",
    difficulty: "Medium",
    description: "Cho `n` cặp ngoặc, hãy tạo ra tất cả các sự kết hợp chuỗi ngoặc đóng mở hợp lệ.",
    codeTemplate: "function generateParenthesis(n: number): string[] {\n    return [];\n};",
    tags: ["String", "Dynamic Programming", "Backtracking"],
    url: "https://leetcode.com/problems/generate-parentheses/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function generateParenthesis(n: number): string[] {\n    return [];\n};",
  },
  {
    id: "33",
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    description: "Tìm chỉ số của mục tiêu `target` trong mảng đã sắp xếp và bị xoay đi tại một trục không xác định bằng thuật giải tối ưu O(log n).",
    codeTemplate: "function search(nums: number[], target: number): number {\n    return -1;\n};",
    tags: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function search(nums: number[], target: number): number {\n    return -1;\n};",
  },
  {
    id: "34",
    title: "Find First and Last Position of Element in Sorted Array",
    difficulty: "Medium",
    description: "Tìm kiếm vị trí bắt đầu và kết thúc của một số mục tiêu cho trước trong mảng đã sắp xếp tăng dần.",
    codeTemplate: "function searchRange(nums: number[], target: number): number[] {\n    return [-1, -1];\n};",
    tags: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function searchRange(nums: number[], target: number): number[] {\n    return [-1, -1];\n};",
  },
  {
    id: "39",
    title: "Combination Sum",
    difficulty: "Medium",
    description: "Cho một mảng các số nguyên phân biệt `candidates` và giá trị `target`, trả về danh sách tất cả các tổ hợp duy nhất các số có tổng bằng `target`.",
    codeTemplate: "function combinationSum(candidates: number[], target: number): number[][] {\n    return [];\n};",
    tags: ["Array", "Backtracking"],
    url: "https://leetcode.com/problems/combination-sum/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function combinationSum(candidates: number[], target: number): number[][] {\n    return [];\n};",
  },
  {
    id: "46",
    title: "Permutations",
    difficulty: "Medium",
    description: "Cho một mảng `nums` gồm các số nguyên riêng biệt, hãy trả về tất cả các hoán vị có thể có của mảng đó.",
    codeTemplate: "function permute(nums: number[]): number[][] {\n    return [];\n};",
    tags: ["Array", "Backtracking"],
    url: "https://leetcode.com/problems/permutations/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function permute(nums: number[]): number[][] {\n    return [];\n};",
  },
  {
    id: "48",
    title: "Rotate Image",
    difficulty: "Medium",
    description: "Xoay một ma trận vuông 2 chiều mô phỏng ảnh một góc 90 độ theo chiều kim đồng hồ ngay tại chỗ (in-place).",
    codeTemplate: "function rotate(matrix: number[][]): void {\n    \n};",
    tags: ["Array", "Math", "Matrix"],
    url: "https://leetcode.com/problems/rotate-image/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function rotate(matrix: number[][]): void {\n    \n};",
  },
  {
    id: "49",
    title: "Group Anagrams",
    difficulty: "Medium",
    description: "Cho một mảng các chuỗi `strs`, hãy nhóm tất cả các từ đảo chữ (anagrams) lại với nhau thành các nhóm độc lập.",
    codeTemplate: "function groupAnagrams(strs: string[]): string[][] {\n    return [];\n};",
    tags: ["Array", "Hash Table", "String", "Sorting"],
    url: "https://leetcode.com/problems/group-anagrams/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function groupAnagrams(strs: string[]): string[][] {\n    return [];\n};",
  },
  {
    id: "53",
    title: "Maximum Subarray",
    difficulty: "Medium",
    description: "Tìm mảng con liên tiếp trong mảng số nguyên `nums` có tổng giá trị lớn nhất lịch sử (Thuật toán Kadane).",
    codeTemplate: "function maxSubArray(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Divide and Conquer", "Dynamic Programming"],
    url: "https://leetcode.com/problems/maximum-subarray/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function maxSubArray(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "55",
    title: "Jump Game",
    difficulty: "Medium",
    description: "Cho một mảng đại diện tầm xa bước nhảy tối đa tại mỗi điểm, kiểm tra xem bạn có thể nhảy đến ô chỉ mục cuối cùng hay không.",
    codeTemplate: "function canJump(nums: number[]): boolean {\n    return false;\n};",
    tags: ["Array", "Dynamic Programming", "Greedy"],
    url: "https://leetcode.com/problems/jump-game/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function canJump(nums: number[]): boolean {\n    return false;\n};",
  },
  {
    id: "56",
    title: "Merge Intervals",
    difficulty: "Medium",
    description: "Cho một mảng chứa các khoảng số nguyên overlap chèn lấn nhau, hãy hợp nhất tất cả các khoảng chồng chéo ấy lại.",
    codeTemplate: "function merge(intervals: number[][]): number[][] {\n    return [];\n};",
    tags: ["Array", "Sorting"],
    url: "https://leetcode.com/problems/merge-intervals/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function merge(intervals: number[][]): number[][] {\n    return [];\n};",
  },
  {
    id: "62",
    title: "Unique Paths",
    difficulty: "Medium",
    description: "Một robot đặt ở góc trên bên trái lưới kích cỡ m x n. Robot chỉ có thể di chuyển xuống dưới hoặc sang phải. Hãy tính tất cả số đường đi độc nhất mà robot có thể đi đến góc dưới bên phải.",
    codeTemplate: "function uniquePaths(m: number, n: number): number {\n    return 0;\n};",
    tags: ["Math", "Dynamic Programming", "Combinatorics"],
    url: "https://leetcode.com/problems/unique-paths/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function uniquePaths(m: number, n: number): number {\n    return 0;\n};",
  },
  {
    id: "73",
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    description: "Cho một ma trận m x n, nếu một phần tử bằng 0, hãy đặt toàn bộ các phần tử thuộc dòng và cột của nó bằng 0.",
    codeTemplate: "function setZeroes(matrix: number[][]): void {\n    \n};",
    tags: ["Array", "Hash Table", "Matrix"],
    url: "https://leetcode.com/problems/set-matrix-zeroes/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function setZeroes(matrix: number[][]): void {\n    \n};",
  },
  {
    id: "74",
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    description: "Tìm kiếm thông minh một số mục tiêu `target` trong ma trận m x n đã được sắp xếp tăng dần từ trái sang phải, dòng trên xuống dưới.",
    codeTemplate: "function searchMatrix(matrix: number[][], target: number): boolean {\n    return false;\n};",
    tags: ["Array", "Binary Search", "Matrix"],
    url: "https://leetcode.com/problems/search-a-2d-matrix/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function searchMatrix(matrix: number[][], target: number): boolean {\n    return false;\n};",
  },
  {
    id: "75",
    title: "Sort Colors",
    difficulty: "Medium",
    description: "Sắp xếp một mảng chứa đỏ, trắng, xanh đại diện bởi 0, 1, 2 tại chỗ sao cho các số có giá trị giống nhau nằm sát nhau (Thuật toán Dutch National Flag).",
    codeTemplate: "function sortColors(nums: number[]): void {\n    \n};",
    tags: ["Array", "Two Pointers", "Sorting"],
    url: "https://leetcode.com/problems/sort-colors/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function sortColors(nums: number[]): void {\n    \n};",
  },
  {
    id: "78",
    title: "Subsets",
    difficulty: "Medium",
    description: "Cho một mảng số nguyên riêng biệt `nums`, hãy trả về tất cả các tập hợp con có thể có (Power Set - tập bền vững chứa mọi tổ hợp con).",
    codeTemplate: "function subsets(nums: number[]): number[][] {\n    return [];\n};",
    tags: ["Array", "Backtracking", "Bit Manipulation"],
    url: "https://leetcode.com/problems/subsets/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function subsets(nums: number[]): number[][] {\n    return [];\n};",
  },
  {
    id: "79",
    title: "Word Search",
    difficulty: "Medium",
    description: "Tìm xem một từ `word` có tồn tại trong lưới ký tự 2D hay không bằng cách di chuyển qua các ô kề cạnh kề kề nhau mà không dùng lại ô đã đi.",
    codeTemplate: "function exist(board: string[][], word: string): boolean {\n    return false;\n};",
    tags: ["Array", "String", "Backtracking", "Matrix"],
    url: "https://leetcode.com/problems/word-search/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function exist(board: string[][], word: string): boolean {\n    return false;\n};",
  },
  {
    id: "98",
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    description: "Cho nút gốc của cây nhị phân, kiểm tra cấu trúc của nó có tuân thủ quy tắc hợp lệ của Cây Tìm Kiếm Nhị Phân (BST) không.",
    codeTemplate: "function isValidBST(root: TreeNode | null): boolean {\n    return false;\n};",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    url: "https://leetcode.com/problems/validate-binary-search-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function isValidBST(root: TreeNode | null): boolean {\n    return false;\n};",
  },
  {
    id: "102",
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    description: "Trả về danh sách duyệt cây nhị phân theo từng tầng cấp độ sâu từ trái sang phải (Level-Order traversal BFS).",
    codeTemplate: "function levelOrder(root: TreeNode | null): number[][] {\n    return [];\n};",
    tags: ["Tree", "Breadth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function levelOrder(root: TreeNode | null): number[][] {\n    return [];\n};",
  },
  {
    id: "105",
    title: "Construct Tree from Preorder and Inorder Traversal",
    difficulty: "Medium",
    description: "Dựng cây nhị phân độc nhất từ hai mảng kết quả duyệt Tiền Thứ (Preorder) và Trung Thứ (Inorder) cho trước.",
    codeTemplate: "function buildTree(preorder: number[], inorder: number[]): TreeNode | null {\n    return null;\n};",
    tags: ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"],
    url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function buildTree(preorder: number[], inorder: number[]): TreeNode | null {\n    return null;\n};",
  },
  {
    id: "122",
    title: "Best Time to Buy and Sell Stock II",
    difficulty: "Medium",
    description: "Bạn có thể thực hiện nhiều giao dịch mua bán cổ phiếu tùy ý. Hãy tìm giá trị lợi nhuận tối đa kiếm được.",
    codeTemplate: "function maxProfit(prices: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Dynamic Programming", "Greedy"],
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function maxProfit(prices: number[]): number {\n    return 0;\n};",
  },
  {
    id: "128",
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    description: "Tìm độ dài của chuỗi các số liên tiếp tăng dần dài nhất được tạo từ các phần tử của mảng số chưa sắp xếp bằng thuật giải O(n).",
    codeTemplate: "function longestConsecutive(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Hash Table", "Union Find"],
    url: "https://leetcode.com/problems/longest-consecutive-sequence/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function longestConsecutive(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "139",
    title: "Word Break",
    difficulty: "Medium",
    description: "Kiểm tra xem chuỗi `s` có thể được phân tách thành các từ nằm trong cuốn từ điển `wordDict` hay không.",
    codeTemplate: "function wordBreak(s: string, wordDict: string[]): boolean {\n    return false;\n};",
    tags: ["Hash Table", "String", "Dynamic Programming", "Trie", "Memoization"],
    url: "https://leetcode.com/problems/word-break/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function wordBreak(s: string, wordDict: string[]): boolean {\n    return false;\n};",
  },
  {
    id: "142",
    title: "Linked List Cycle II",
    difficulty: "Medium",
    description: "Nếu có vòng lặp chu trình trong danh sách liên kết, hãy tìm và trả về nút bắt đầu nơi xảy ra cuộc lặp vòng đó. Ngược lại trả về null.",
    codeTemplate: "function detectCycle(head: ListNode | null): ListNode | null {\n    return null;\n};",
    tags: ["Hash Table", "Linked List", "Two Pointers"],
    url: "https://leetcode.com/problems/linked-list-cycle-ii/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function detectCycle(head: ListNode | null): ListNode | null {\n    return null;\n};",
  },
  {
    id: "150",
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    description: "Tính giá trị biểu thức số học viết theo ký pháp Ba Lan ngược (RPN) dùng cấu trúc Stack chuẩn.",
    codeTemplate: "function evalRPN(tokens: string[]): number {\n    return 0;\n};",
    tags: ["Array", "Math", "Stack"],
    url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function evalRPN(tokens: string[]): number {\n    return 0;\n};",
  },
  {
    id: "152",
    title: "Maximum Product Subarray",
    difficulty: "Medium",
    description: "Tìm mảng con liên tiếp trong mảng số nguyên có tích các chữ số là lớn nhất.",
    codeTemplate: "function maxProduct(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/maximum-product-subarray/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function maxProduct(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "153",
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    description: "Tìm số nhỏ nhất trong mảng đã được sắp xếp tăng dần và bị xoay đi một trục ngẫu nhiên.",
    codeTemplate: "function findMin(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Binary Search"],
    url: "https://leetcode.com/problems/find-min-in-rotated-sorted-array/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function findMin(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "155",
    title: "Min Stack",
    difficulty: "Medium",
    description: "Thiết kế một cấu trúc Stack hỗ trợ các hàm nạp dữ liệu, lấy ra và truy xuất giá trị nhỏ nhất hiện tại trong thời gian O(1).",
    codeTemplate: "class MinStack {\n    constructor() {}\n    push(val: number): void {}\n    pop(): void {}\n    top(): number { return 0; }\n    getMin(): number { return 0; }\n};",
    tags: ["Stack", "Design"],
    url: "https://leetcode.com/problems/min-stack/",
    status: "Todo",
    solvedCount: 0,
    userCode: "class MinStack {\n    constructor() {}\n    push(val: number): void {}\n    pop(): void {}\n    top(): number { return 0; }\n    getMin(): number { return 0; }\n};",
  },
  {
    id: "167",
    title: "Two Sum II - Input Array Is Sorted",
    difficulty: "Medium",
    description: "Tìm hai nút có tổng bằng target trong mảng số nguyên đã sắp xếp tăng dần bằng kỹ thuật hai con trỏ tối ưu O(1) bộ nhớ.",
    codeTemplate: "function twoSum(numbers: number[], target: number): number[] {\n    return [];\n};",
    tags: ["Array", "Two Pointers", "Binary Search"],
    url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function twoSum(numbers: number[], target: number): number[] {\n    return [];\n};",
  },
  {
    id: "198",
    title: "House Robber",
    difficulty: "Medium",
    description: "Bạn là siêu trộm đi cướp các ngôi nhà cạnh nhau trên đường nằm thẳng hàng, nhưng không thể cướp hai nhà liền kề. Hãy tối ưu điểm trộm nhiều tiền nhất.",
    codeTemplate: "function rob(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/house-robber/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function rob(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "200",
    title: "Number of Islands",
    difficulty: "Medium",
    description: "Cho bản đồ lưới nhị phân m x n gồm các vùng đất liền '1' và nước '0', hãy tính số lượng đảo độc lập.",
    codeTemplate: "function numIslands(grid: string[][]): number {\n    return 0;\n};",
    tags: ["Array", "Depth-First Search", "Breadth-First Search", "Union Find", "Matrix"],
    url: "https://leetcode.com/problems/number-of-islands/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function numIslands(grid: string[][]): number {\n    return 0;\n};",
  },
  {
    id: "207",
    title: "Course Schedule",
    difficulty: "Medium",
    description: "Cho tổng số khóa học cần hoàn thành kèm mảng ràng buộc môn tiên quyết, xác định xem có thể hoàn thành toàn bộ chương trình học không (Phát hiện chu trình đồ thị có hướng).",
    codeTemplate: "function canFinish(numCourses: number, prerequisites: number[][]): boolean {\n    return false;\n};",
    tags: ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
    url: "https://leetcode.com/problems/course-schedule/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function canFinish(numCourses: number, prerequisites: number[][]): boolean {\n    return false;\n};",
  },
  {
    id: "208",
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    description: "Hiện thực cấu trúc cây tiền tố Trie lưu trữ từ vựng hiệu quả hỗ trợ các hàm chèn từ, tìm kiếm từ, và tìm tiền tố phù hợp.",
    codeTemplate: "class Trie {\n    constructor() {}\n    insert(word: string): void {}\n    search(word: string): boolean { return false; }\n    startsWith(prefix: string): boolean { return false; }\n};",
    tags: ["Design", "Trie"],
    url: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "class Trie {\n    constructor() {}\n    insert(word: string): void {}\n    search(word: string): boolean { return false; }\n    startsWith(prefix: string): boolean { return false; }\n};",
  },
  {
    id: "230",
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    description: "Tìm phần tử có giá trị nhỏ thứ `k` trong một cây tìm kiếm nhị phân (BST).",
    codeTemplate: "function kthSmallest(root: TreeNode | null, k: number): number {\n    return 0;\n};",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function kthSmallest(root: TreeNode | null, k: number): number {\n    return 0;\n};",
  },
  {
    id: "235",
    title: "Lowest Common Ancestor of a BST",
    difficulty: "Medium",
    description: "Tìm nút tổ tiên chung thấp nhất (LCA) của hai nút cho trước trong cây tìm kiếm nhị phân BST.",
    codeTemplate: "function lowestCommonAncestor(root: TreeNode | null, p: TreeNode | null, q: TreeNode | null): TreeNode | null {\n    return null;\n};",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function lowestCommonAncestor(root: TreeNode | null, p: TreeNode | null, q: TreeNode | null): TreeNode | null {\n    return null;\n};",
  },
  {
    id: "236",
    title: "Lowest Common Ancestor of a Binary Tree",
    difficulty: "Medium",
    description: "Tìm nút tổ tiên chung thấp nhất (LCA) của hai nút cho trước trong một cây nhị phân thông thường.",
    codeTemplate: "function lowestCommonAncestor(root: TreeNode | null, p: TreeNode | null, q: TreeNode | null): TreeNode | null {\n    return null;\n};",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function lowestCommonAncestor(root: TreeNode | null, p: TreeNode | null, q: TreeNode | null): TreeNode | null {\n    return null;\n};",
  },
  {
    id: "238",
    title: "Product of Array Except Self",
    difficulty: "Medium",
    description: "Trả về mảng kết quả sao cho tại mỗi phần tử chỉ số i bằng tích của tất cả các phần tử khác ngoại trừ chính nó, không dùng phép chia.",
    codeTemplate: "function productExceptSelf(nums: number[]): number[] {\n    return [];\n};",
    tags: ["Array", "Prefix Sum"],
    url: "https://leetcode.com/problems/product-of-array-except-self/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function productExceptSelf(nums: number[]): number[] {\n    return [];\n};",
  },
  {
    id: "287",
    title: "Find the Duplicate Number",
    difficulty: "Medium",
    description: "Cho một mảng có chứa n+1 số nguyên trong khoảng [1, n], tìm ra số nguyên bị trùng lặp duy nhất trong mảng mà không đổi mảng.",
    codeTemplate: "function findDuplicate(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Two Pointers", "Binary Search", "Bit Manipulation"],
    url: "https://leetcode.com/problems/find-the-duplicate-number/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function findDuplicate(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "300",
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    description: "Tìm độ dài của dãy con tăng dần dài nhất trong mảng số nguyên `nums`.",
    codeTemplate: "function lengthOfLIS(nums: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Binary Search", "Dynamic Programming"],
    url: "https://leetcode.com/problems/longest-increasing-subsequence/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function lengthOfLIS(nums: number[]): number {\n    return 0;\n};",
  },
  {
    id: "322",
    title: "Coin Change",
    difficulty: "Medium",
    description: "Hãy tìm số lượng đồng xu ít nhất cần dùng để tạo thành tổng tiền `amount` dựa trên các mệnh giá đồng xu cho trước.",
    codeTemplate: "function coinChange(coins: number[], amount: number): number {\n    return -1;\n};",
    tags: ["Array", "Dynamic Programming", "Breadth-First Search"],
    url: "https://leetcode.com/problems/coin-change/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function coinChange(coins: number[], amount: number): number {\n    return -1;\n};",
  },
  {
    id: "347",
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    description: "Trả về `k` phần tử xuất hiện thường xuyên nhất trong một mảng số nguyên.",
    codeTemplate: "function topKFrequent(nums: number[], k: number): number[] {\n    return [];\n};",
    tags: ["Array", "Hash Table", "Divide and Conquer", "Sorting", "Priority Queue", "Quickselect"],
    url: "https://leetcode.com/problems/top-k-frequent-elements/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function topKFrequent(nums: number[], k: number): number[] {\n    return [];\n};",
  },
  {
    id: "416",
    title: "Partition Equal Subset Sum",
    difficulty: "Medium",
    description: "Kiểm tra xem một mảng số nguyên dương có thể được phân chia thành hai tập con có tổng giá trị bằng nhau không.",
    codeTemplate: "function canPartition(nums: number[]): boolean {\n    return false;\n};",
    tags: ["Array", "Dynamic Programming"],
    url: "https://leetcode.com/problems/partition-equal-subset-sum/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function canPartition(nums: number[]): boolean {\n    return false;\n};",
  },
  {
    id: "438",
    title: "Find All Anagrams in a String",
    difficulty: "Medium",
    description: "Nhận vào chuỗi s và chuỗi p, tìm tất cả chỉ số bắt đầu của các chuỗi con của s là đảo chữ (anagram) của p.",
    codeTemplate: "function findAnagrams(s: string, p: string): number[] {\n    return [];\n};",
    tags: ["Hash Table", "String", "Sliding Window"],
    url: "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function findAnagrams(s: string, p: string): number[] {\n    return [];\n};",
  },
  {
    id: "647",
    title: "Palindromic Substrings",
    difficulty: "Medium",
    description: "Tính tổng số lượng chuỗi con đối xứng đang tồn tại bên trong chuỗi s.",
    codeTemplate: "function countSubstrings(s: string): number {\n    return 0;\n};",
    tags: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/palindromic-substrings/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function countSubstrings(s: string): number {\n    return 0;\n};",
  },
  {
    id: "739",
    title: "Daily Temperatures",
    difficulty: "Medium",
    description: "Trả về mảng kết quả số ngày cần chờ đến khi có nhiệt độ ấm hơn ứng với mỗi ngày qua Monotonic Stack.",
    codeTemplate: "function dailyTemperatures(temperatures: number[]): number[] {\n    return [];\n};",
    tags: ["Array", "Stack", "Monotonic Stack"],
    url: "https://leetcode.com/problems/daily-temperatures/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function dailyTemperatures(temperatures: number[]): number[] {\n    return [];\n};",
  },
  {
    id: "1143",
    title: "Longest Common Subsequence",
    difficulty: "Medium",
    description: "Tìm độ dài của chuỗi con chung dài nhất giữa hai chuỗi văn bản text1 và text2 bằng thuật giải quy hoạch động DP.",
    codeTemplate: "function longestCommonSubsequence(text1: string, text2: string): number {\n    return 0;\n};",
    tags: ["String", "Dynamic Programming"],
    url: "https://leetcode.com/problems/longest-common-subsequence/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function longestCommonSubsequence(text1: string, text2: string): number {\n    return 0;\n};",
  },

  // ==========================================
  // HARD PROBLEMS (86 to 102)
  // ==========================================
  {
    id: "4",
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    description: "Cho hai mảng đã sắp xếp `nums1` và `nums2` kích cỡ m và n, trả về trung vị của hai mảng đã trộn này trong độ phức tạp tối đa O(log(m+n)).",
    codeTemplate: "function findMedianSortedArrays(nums1: number[], nums2: number[]): number {\n    return 0.0;\n};",
    tags: ["Array", "Binary Search", "Divide and Conquer"],
    url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function findMedianSortedArrays(nums1: number[], nums2: number[]): number {\n    return 0.0;\n};",
  },
  {
    id: "23",
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    description: "Nhận một mảng chứa k danh sách liên kết đã sắp xếp, trộn tất cả các danh sách ấy thành một danh sách liên kết duy nhất được sắp xếp tăng dần.",
    codeTemplate: "function mergeKLists(lists: Array<ListNode | null>): ListNode | null {\n    return null;\n};",
    tags: ["Linked List", "Divide and Conquer", "Heap (Priority Queue)", "Merge Sort"],
    url: "https://leetcode.com/problems/merge-k-sorted-lists/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function mergeKLists(lists: Array<ListNode | null>): ListNode | null {\n    return null;\n};",
  },
  {
    id: "42",
    title: "Trapping Rain Water",
    difficulty: "Hard",
    description: "Tính lượng nước mưa tối đa có thể đọng lại trên mô hình bản đồ độ cao các cột đơn vị có sẵn.",
    codeTemplate: "function trap(height: number[]): number {\n    return 0;\n};",
    solution: "function trap(height: number[]): number {\n    let left = 0, right = height.length - 1;\n    let leftMax = 0, rightMax = 0, total = 0;\n    while (left < right) {\n        if (height[left] < height[right]) {\n            if (height[left] >= leftMax) leftMax = height[left];\n            else total += leftMax - height[left];\n            left++;\n        } else {\n            if (height[right] >= rightMax) rightMax = height[right];\n            else total += rightMax - height[right];\n            right--;\n        }\n    }\n    return total;\n};",
    tags: ["Array", "Two Pointers", "Dynamic Programming", "Stack", "Monotonic Stack"],
    url: "https://leetcode.com/problems/trapping-rain-water/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function trap(height: number[]): number {\n    return 0;\n};",
  },
  {
    id: "76",
    title: "Minimum Window Substring",
    difficulty: "Hard",
    description: "Tìm chuỗi con ngắn nhất trong s chứa đầy đủ tất cả ký tự có trong chuỗi t bằng kỹ thuật hai con trỏ trượt độ phức tạp tuyến tính.",
    codeTemplate: "function minWindow(s: string, t: string): string {\n    return \"\";\n};",
    tags: ["Hash Table", "String", "Sliding Window"],
    url: "https://leetcode.com/problems/minimum-window-substring/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function minWindow(s: string, t: string): string {\n    return \"\";\n};",
  },
  {
    id: "84",
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    description: "Cho một mảng chiều cao biểu đồ thanh, tìm diện tích lớn nhất của hình chữ nhật có thể dựng được trong biểu đồ.",
    codeTemplate: "function largestRectangleArea(heights: number[]): number {\n    return 0;\n};",
    tags: ["Array", "Stack", "Monotonic Stack"],
    url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function largestRectangleArea(heights: number[]): number {\n    return 0;\n};",
  },
  {
    id: "124",
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    description: "Hãy tìm tổng giá trị lớn nhất của đường đi bất kỳ giữa hai nút bất kỳ trong một cây nhị phân cây.",
    codeTemplate: "function maxPathSum(root: TreeNode | null): number {\n    return 0;\n};",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function maxPathSum(root: TreeNode | null): number {\n    return 0;\n};",
  },
  {
    id: "239",
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    description: "Trả về mảng chứa số lớn nhất tại mỗi vị trí cửa sổ trượt kích cỡ k di chuyển dọc từ đầu đến cuối mảng.",
    codeTemplate: "function maxSlidingWindow(nums: number[], k: number): number[] {\n    return [];\n};",
    tags: ["Array", "Queue", "Sliding Window", "Heap (Priority Queue)", "Monotonic Queue"],
    url: "https://leetcode.com/problems/sliding-window-maximum/",
    status: "Todo",
    solvedCount: 0,
    userCode: "function maxSlidingWindow(nums: number[], k: number): number[] {\n    return [];\n};",
  },
  {
    id: "295",
    title: "Find Median from Data Stream",
    difficulty: "Hard",
    description: "Thiết kế lớp chứa luồng số nhận liên tiếp số nguyên đầu vào và trả về trung vị của luồng số đang lưu trong thời gian thực tối ưu.",
    codeTemplate: "class MedianFinder {\n    constructor() {}\n    addNum(num: number): void {}\n    findMedian(): number { return 0.0; }\n};",
    tags: ["Two Pointers", "Design", "Sorting", "Heap (Priority Queue)", "Data Stream"],
    url: "https://leetcode.com/problems/find-median-from-data-stream/",
    status: "Todo",
    solvedCount: 0,
    userCode: "class MedianFinder {\n    constructor() {}\n    addNum(num: number): void {}\n    findMedian(): number { return 0.0; }\n};",
  }
];
